-- HR Salary Analysis
-- Departament ve vezife uzre maas berabersizliyi analizi
-- Oracle HR schema


-- 1. Departament uzre orta, min, max maas
SELECT 
    d.DEPARTMENT_NAME,
    COUNT(e.EMPLOYEE_ID) AS TOTAL_EMPLOYEES,
    ROUND(AVG(e.SALARY), 2) AS AVG_SALARY,
    MIN(e.SALARY) AS MIN_SALARY,
    MAX(e.SALARY) AS MAX_SALARY
FROM HR.EMPLOYEES e
JOIN HR.DEPARTMENTS d 
    ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
GROUP BY d.DEPARTMENT_NAME
ORDER BY AVG_SALARY DESC;


-- 2. Job title uzre maas gap-i (max-min ferqi)
SELECT 
    j.JOB_TITLE,
    COUNT(e.EMPLOYEE_ID) AS TOTAL_EMPLOYEES,
    ROUND(AVG(e.SALARY), 2) AS AVG_SALARY,
    MAX(e.SALARY) - MIN(e.SALARY) AS SALARY_GAP
FROM HR.EMPLOYEES e
JOIN HR.JOBS j 
    ON e.JOB_ID = j.JOB_ID
GROUP BY j.JOB_TITLE
ORDER BY SALARY_GAP DESC;


-- 3. Tecrube ile maas elaqesi
SELECT 
    e.EMPLOYEE_ID,
    e.FIRST_NAME || ' ' || e.LAST_NAME AS FULL_NAME,
    d.DEPARTMENT_NAME,
    ROUND(MONTHS_BETWEEN(SYSDATE, e.HIRE_DATE)/12, 1) AS YEARS_EXPERIENCE,
    e.SALARY
FROM HR.EMPLOYEES e
JOIN HR.DEPARTMENTS d 
    ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
ORDER BY YEARS_EXPERIENCE DESC;


-- 4. Departament uzre umumi maas xerci (treemap ucun)
SELECT 
    d.DEPARTMENT_NAME,
    SUM(e.SALARY) AS TOTAL_SALARY_COST,
    COUNT(e.EMPLOYEE_ID) AS TOTAL_EMPLOYEES
FROM HR.EMPLOYEES e
JOIN HR.DEPARTMENTS d 
    ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
GROUP BY d.DEPARTMENT_NAME
ORDER BY TOTAL_SALARY_COST DESC;
